CASPAR/Areas/Administrator/Pages/Campuses/Index.cshtml.cs
using CASPAR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CASPAR.Areas.Administrator.Pages.Campuses
{
	[Authorize(Roles = StaticDetails.Admin)]
	public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CASPAR/Areas/Administrator/Pages/Campuses/Upsert.cshtml.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.ApplicationCore.ViewModels;
using CASPAR.DataAccess;
using CASPAR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CASPAR.Areas.Administrator.Pages.Campuses
{
	[Authorize(Roles = StaticDetails.Admin)]
    public class UpsertModel : PageModel
    {
		private readonly UnitOfWork _unitOfWork;

		[BindProperty]
		public Campus Campus { get; set; }

		public UpsertModel(UnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public void OnGet(int? ID)
        {
			Campus = new Campus();
			if(ID != 0 && ID != null)
			{
				Campus = _unitOfWork.Campus.GetById(ID);
			}
		}

		[HttpPost]
		public IActionResult OnPostCreateCampus()
		{
			_unitOfWork.Campus.Add(Campus);
			return RedirectToPage("./Index");
		}

		[HttpPost]
		public IActionResult OnPostEditCampus()
		{
			_unitOfWork.Campus.Update(Campus);

			return RedirectToPage("./Index");
		}

		[HttpPost]
		public IActionResult OnPostDeleteCampus()
		{
			_unitOfWork.Campus.Delete(Campus);

			return RedirectToPage("./Index");
		}

	}
}

CASPAR/Areas/Administrator/Pages/Semester_Template/Upsert.cshtml.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.ApplicationCore.ViewModels;
using CASPAR.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CASPAR.Areas.Administrator.Pages.Semester_Template
{
    public class UpsertModel : PageModel
    {
		private readonly UnitOfWork _unitOfWork;


        [BindProperty]
        public TemplateVM TemplateVM { get; set; }
		
        public IEnumerable<SemesterTemplate> SemesterTemplateList;
        public List<Course> CourseList { get; set; }

		public UpsertModel(UnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult OnGet(int? id)
		{
			TemplateVM = new TemplateVM();
			TemplateVM.Template = new Template();
			TemplateVM.SemesterTemplate = new SemesterTemplate();
			//TemplateVM.SemesterTemplate = null;

            SemesterTemplateList = new List<SemesterTemplate>();

			if (id == null || id == 0) // create mode
			{
				TemplateVM.Template = new Template();
				TemplateVM.Template.TemplateID = 0;
				return Page();
			}

            SemesterTemplateList = _unitOfWork.SemesterTemplate.GetAll(s => s.TemplateID == id);

			CourseList = _unitOfWork.Course.GetAll().ToList();

			//edit mode
			if (id != 0)
			{
				TemplateVM.Template = _unitOfWork.Template.GetById(id);
			}

			if (TemplateVM.Template == null)
			{
				return NotFound();
			}

			//create new mode
			return Page();
		}

		public IActionResult OnPostTemplate(int? id)
		{

            //if this is a new template
            if (TemplateVM.Template.TemplateID == 0)
			{
				_unitOfWork.Template.Add(TemplateVM.Template);  // Adds to memory
				TempData["success"] = "Template added Successfully";
            }
			//if schedule exists
			else
			{
				_unitOfWork.Template.Update(TemplateVM.Template);
				TempData["success"] = "Template updated Successfully";
			}
			_unitOfWork.Commit(); // Saves to database

			// Reload the page
			return OnGet(TemplateVM.Template.TemplateID);

        }

		public IActionResult OnPostSemesterTemplate(int? id)
        {

            //if this is a new SemesterTemplate
            if (TemplateVM.SemesterTemplate.SemesterTemplateID == 0)
			{
				_unitOfWork.SemesterTemplate.Add(TemplateVM.SemesterTemplate);  // Adds to memory
				TempData["success"] = "SemesterTemplate added Successfully";
			}
			//if schedule exists
			else
			{
				_unitOfWork.SemesterTemplate.Update(TemplateVM.SemesterTemplate);
				TempData["success"] = "SemesterTemplate updated Successfully";
			}
			_unitOfWork.Commit(); // Saves to database

			// Reload the page
			return RedirectToPage("", new { id = id });
        }

	}
}

CASPAR/Areas/Instructor/Pages/Preferences/Upsert.cshtml.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.ApplicationCore.ViewModels;
using CASPAR.DataAccess;
using CASPAR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace CASPAR.Areas.Instructors.Pages.Preferences
{
	[Authorize(Roles = StaticDetails.Instructor + "," + StaticDetails.Student)]
	public class UpsertModel : PageModel
    {
        private UnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        [BindProperty]
        public InstructorPreferenceAddVM InstructorPreferenceAddVM { get; set; }

        public List<TimeOfDay> TimeOfTheDay { get; set; }
        public List<DayOfTheWeek> DayOfTheWeek { get; set; }
        public List<Modality> Modalities { get; set; }
        public List<Campus> Campuses { get; set; }
        public List<InstructorPreferences> PreviousPreferences { get; set; }
		public int LowestModelPreferenceValue { get; set; }

		public UpsertModel(UnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult OnGet(int? CourseID, int? SemesterID, int? PreferenceID)
        {
            // Check if we are updating or creating a new preference
            InstructorPreferenceAddVM = new InstructorPreferenceAddVM();
            if (PreferenceID != null)
            {
                InstructorPreferences ip = _unitOfWork.InstructorPreferences.GetById(PreferenceID);
                InstructorPreferenceAddVM.Preference = ip;

                InstructorPreferenceAddVM.Course = new Course();
                InstructorPreferenceAddVM.Course = _unitOfWork.Course.Get(u => u.CourseID == ip.CourseID);
                CourseID = ip.CourseID;

                InstructorPreferenceAddVM.Semester = new Semester();
                InstructorPreferenceAddVM.Semester = _unitOfWork.Semester.Get(u => u.Id == ip.SemesterID);
                SemesterID = ip.SemesterID;
            }
            else if (InstructorPreferenceAddVM.Preference == null)
            {
                InstructorPreferenceAddVM.Preference = new InstructorPreferences();

                InstructorPreferenceAddVM.Course = new Course();
                InstructorPreferenceAddVM.Course = _unitOfWork.Course.Get(u => u.CourseID == CourseID);

                InstructorPreferenceAddVM.Semester = new Semester();
                InstructorPreferenceAddVM.Semester = _unitOfWork.Semester.Get(u => u.Id == SemesterID);
            }

            // Get all for selects
            TimeOfTheDay = new List<TimeOfDay>();
            TimeOfTheDay = _unitOfWork.TimeOfDay.GetAll().ToList();

            DayOfTheWeek = new List<DayOfTheWeek>();
            DayOfTheWeek = _unitOfWork.DAY_OF_WEEK.GetAll().ToList();

            Modalities = new List<Modality>();
            Modalities = _unitOfWork.Modality.GetAll().ToList();

            Campuses = new List<Campus>();
            Campuses = _unitOfWork.Campus.GetAll().ToList();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's Id
            Instructor AppUser = _unitOfWork.Instructor.Get(u => u.Id == userId);

            PreviousPreferences = new List<InstructorPreferences>();
            PreviousPreferences = _unitOfWork.InstructorPreferences.GetAll(u => u.WNumber == AppUser.Id, orderBy: u => u.PreferencesRank, includes: "Course").ToList();
            PreviousPreferences.RemoveAll(u => u.SemesterID != SemesterID);

            // Add the userId to the from
            InstructorPreferenceAddVM.Preference.WNumber = AppUser.Id;

			LowestModelPreferenceValue = PreviousPreferences.Count + 1; // Get the lowest and then one, or if none just one

			return Page();
        }

        [HttpPost]
        public IActionResult OnPostCreatePreference()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's Id
            Instructor AppUser = _unitOfWork.Instructor.Get(u => u.Id == userId);

            // Set Preference equal to the other values
            InstructorPreferenceAddVM.Preference.WNumber = AppUser.Id;
            InstructorPreferenceAddVM.Preference.SemesterID = InstructorPreferenceAddVM.Semester.Id;
            InstructorPreferenceAddVM.Preference.CourseID = InstructorPreferenceAddVM.Course.CourseID;

            _unitOfWork.Preferences.addPreferencesRank(InstructorPreferenceAddVM.Preference);
            _unitOfWork.Commit();

            return RedirectToPage("/Preferences/Index", new { Semester = InstructorPreferenceAddVM.Semester.Id});
        }

        [HttpPost]
        public IActionResult OnPostEditPreference()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's Id
            Instructor AppUser = _unitOfWork.Instructor.Get(u => u.Id == userId);

            // Set Preference equal to the other values
            InstructorPreferenceAddVM.Preference.SemesterID = InstructorPreferenceAddVM.Semester.Id;
            InstructorPreferenceAddVM.Preference.CourseID = InstructorPreferenceAddVM.Course.CourseID;

            _unitOfWork.Preferences.updatePreferencesRank(InstructorPreferenceAddVM.Preference);
            _unitOfWork.Commit();
            //_unitOfWork.InstructorPreferences.Update(InstructorPreferenceAddVM.Preference);
            //_unitOfWork.Commit();

            return RedirectToPage("/Preferences/Index", new { Semester = InstructorPreferenceAddVM.Semester.Id });
		}

        [HttpPost]
        public IActionResult OnPostDeletePreference()
        {
            _unitOfWork.Preferences.deletePreferencesRank(InstructorPreferenceAddVM.Preference);
            _unitOfWork.Commit();

            return RedirectToPage("/Preferences/Index", new { Semester = InstructorPreferenceAddVM.Semester.Id });
		}

    }
}

CASPAR/Areas/ProgramCoordinator/Pages/Semester_Schedule/Upsert.cshtml.cs
using CASPAR.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CASPAR.ApplicationCore.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CASPAR.Areas.ProgramCoordinator.Pages.Semester_Schedule
{
    public class UpsertModel : PageModel
    {
        private readonly UnitOfWork _unitOfWork;
        [BindProperty]
        public SemesterSchedule objSemesterSchedule { get; set; }

		public IEnumerable<SelectListItem> SemesterTemplateList { get; set; }
		public IEnumerable<SelectListItem> StatusList { get; set; }
        public IEnumerable<SelectListItem> SemesterList { get; set; }

        public UpsertModel(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult OnGet(int? id)
        {
            objSemesterSchedule = new SemesterSchedule();
			SemesterTemplateList = _unitOfWork.SemesterTemplate.GetAll().Select(s => new SelectListItem
			{
				Text = s.Template.TemplateName,
				Value = s.SemesterTemplateID.ToString()
			});
			StatusList = _unitOfWork.Status.GetAll().Select(s => new SelectListItem
            {
                Text = s.StatusType,
                Value = s.StatusID.ToString()
            });
            SemesterList = _unitOfWork.Semester.GetAll().Select(s => new SelectListItem
            {
                Text = s.SemesterName+ " " + s.SemesterYear,
                Value = s.Id.ToString()
            });

            if (id == null || id == 0) // create mode
            {
                return Page();
            }

            //edit mode
            if (id != 0)
            {
                objSemesterSchedule = _unitOfWork.SemesterSchedule.GetById(id);
            }

            if (objSemesterSchedule == null)
            {
                return NotFound();
            }

            //create new mode
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //if this is a new schedule
            if (objSemesterSchedule.SemesterScheduleID == 0)
            {
                _unitOfWork.SemesterSchedule.Add(objSemesterSchedule);  // Adds to memory
                TempData["success"] = "Semester Schedule added Successfully";
            }
            //if schedule exists
            else
            {
                _unitOfWork.SemesterSchedule.Update(objSemesterSchedule);
                TempData["success"] = "Semester Schedule updated Successfully";
            }
            _unitOfWork.Commit(); // Saves to database

            return RedirectToPage("./Upsert");
        }
    }
}

CASPAR/Areas/ProgramCoordinator/Pages/Tickets/Upsert.cshtml.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.ApplicationCore.ViewModels;
using CASPAR.DataAccess;
using CASPAR.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace CASPAR.Areas.ProgramCoordinator.Pages.Tickets
{
	[Authorize]
	public class UpsertModel : PageModel
    {
        private readonly UnitOfWork _unitOfWork;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		[BindProperty]
		public TicketVM TicketVM { get; set; }

        public UpsertModel(UnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
			_userManager = userManager;
			_roleManager = roleManager;
		}


		[Authorize(Roles = StaticDetails.PC + "," + StaticDetails.Instructor)]
		public IActionResult OnGet(int? id)
        {

			TicketVM = new TicketVM()
			{
				Ticket = new Ticket(),
				Instructor = new Instructor(),
			};

			//edit mode
			if (id != 0)
			{
				TicketVM.Ticket = _unitOfWork.Tickets.GetById(id);
				TicketVM.Instructor = _unitOfWork.Instructor.Get(i => i.Id == TicketVM.Ticket.WNumber);
			}
			else
			{
				string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's Id
				Instructor AppUser = _unitOfWork.Instructor.Get(u => u.Id == userId);

				TicketVM.Instructor = AppUser;
			}

			//if (objTicket == null)
			//{
			//	return NotFound();
			//}

			//create new mode
			return Page();
		}


		[HttpPost]
		[Authorize(Roles = StaticDetails.PC + "," + StaticDetails.Instructor)]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> OnPostCreateTicket()
		{
			Instructor? objInstructor = TicketVM.Instructor;
			Ticket objTicket = TicketVM.Ticket;

			// If it is an admin creating the ticket find who they are looking for
			if(objInstructor.Id == null)
			{
				objInstructor = _unitOfWork.Instructor.Get(u => u.WNumber == objInstructor.WNumber);
				// Check if the objInstructor exists
				if(objInstructor == null)
				{
					//TempData["error"] = "Error with WNumber.";
					return RedirectToPage("Upsert", new { Id = 0 });
				}
			}


			objTicket.WNumber = objInstructor.Id;

			_unitOfWork.Tickets.Add(objTicket);
			_unitOfWork.Commit();

			// Get current logged in user
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's Id
			ApplicationUser AppUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
			var roles =  await _userManager.GetRolesAsync(AppUser);

			// IF PC return to ticket index
			if (roles.Contains(StaticDetails.PC))
			{
				return RedirectToPage("./Index");
			}
			// Else return to the main index page
			else
			{
				return RedirectToPage("/Index");
			}
		}


		[HttpPost]
		[Authorize(Roles = StaticDetails.PC)]
		[ValidateAntiForgeryToken]
		public IActionResult OnPostEditTicket()
		{
			//return Page();
			Ticket ticket = TicketVM.Ticket;

			_unitOfWork.Tickets.Update(ticket);
			_unitOfWork.Commit();

			return RedirectToPage("./Index");
		}


		[HttpPost]
		[Authorize(Roles = StaticDetails.PC)]
		[ValidateAntiForgeryToken]
		public IActionResult OnPostDeleteTicket()
		{
			//return Page();
			Ticket ticket = TicketVM.Ticket;

			_unitOfWork.Tickets.Delete(ticket);
			_unitOfWork.Commit();

			return RedirectToPage("./Index");
		}
	}
}

CASPAR/Areas/Administrator/Pages/Campuses/Index.cshtml
@page
@model CASPAR.Areas.Administrator.Pages.Campuses.IndexModel
@{
	ViewData["Title"] = "Campus";
}
<div class="row">
	<!-- Name of current dashboard-->
	<h4>Campus</h4>
</div>
<!-- Create a new card-->
<div class="row">
	<div class="col-4 mb-3">
		<div class="card shadow">
			<div class="card-body py-5">
				<h5>Create New Campus</h5>
				<a class="btn btn-outline-primary" asp-area="Administrator" asp-page="/Campuses/Upsert">Create</a>
			</div>
		</div>
	</div>
</div>

<!-- Create a new card-->
<!-- Create a new card-->
<div class="row">
	<div class="col-12 mb-3">
		<div class="card">
			<div class="card-body py-5">
				@(Html.Awe().Grid("DisplayCampus")
					.Mod(o => o.Main())
					.Columns(
					new Column { Bind = "CampusName", Header = "Name" },
					new Column { Bind = "Address1,SafeAddress2", Header = "Address", ClientFormat = ".(Address)" },
					new Column { Bind = "State" },
					new Column { ClientFormatFunc = "editBtn" }
					)
					.Url(Url.Action(nameof(CASPAR.Areas.Administrator.Controllers.CampusController.GetAll), "Campus"))
					)
			</div>
		</div>
	</div>
</div>

@section Scripts{
	<script>
		function editBtn(model) {
			let number = model.id;
			return `<a class="btn btn-outline-primary" href="/Administrator/Campuses/Upsert?ID=${number}">Edit</a>`;
		}
	</script>
}

CASPAR/Areas/Administrator/Pages/Campuses/Upsert.cshtml
@page
@model CASPAR.Areas.Administrator.Pages.Campuses.UpsertModel
@{
	ViewData["Title"] = "Campus";
}
<div class="row">
	<!-- Name of current dashboard-->
	<h4>Campus</h4>
</div>

<!-- Create a new card-->
<div class="row">
	<div class="col-12 mb-3">
		<div class="card">
			<div class="card-body py-5">
				<form method="post" asp-page="Upsert" enctype="multipart/form-data" id="campusForm" onsubmit="return validateForm()">

					<!-- Campus Name -->
					<label asp-for="Campus.CampusName">Campus Name</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.CampusName" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.CampusName" class="text-danger"></span>
					</div>

					<!-- Address 1 -->
					<label asp-for="Campus.Address1">Address line 1</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.Address1" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.Address1" class="text-danger"></span>
					</div>

					<!-- Address 2 -->
					<label asp-for="Campus.Address2">Address line 2</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.Address2" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.Address2" class="text-danger"></span>
					</div>

					<!-- City -->
					<label asp-for="Campus.City">City</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.City" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.City" class="text-danger"></span>
					</div>

					<!-- State -->
					<label asp-for="Campus.State">State</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.State" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.State" class="text-danger"></span>
					</div>

					<!-- Country -->
					<label asp-for="Campus.Country">Country</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.Country" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.Country" class="text-danger"></span>
					</div>

					<!-- Country -->
					<label asp-for="Campus.Zip">ZIP / Postal Code</label>
					<div class="input-group flex-nowrap pb-2">
						@*						<span class="input-group-text bg-primary">
						<i class="bi bi-ticket-perforated text-white"></i>
						</span>
						*@
						<input asp-for="Campus.Zip" class="form-control" />
					</div>
					<div class="row">
						<span asp-validation-for="@Model.Campus.Zip" class="text-danger"></span>
					</div>

					<!-- End of Submit buttons -->
					<!-- Start of Hidden Inputs-->
					@if (Model.Campus.Id != 0)
					{
						<input type="hidden" asp-for="Campus.Id" class="form-control" />
					}
					<!-- End of Hidden Inputs-->
					<!-- Start of Submit buttons -->
					<div class="d-flex">
						@if (Model.Campus.Id != 0)
						{
							<div class="">
								<button type="button" class="btn btn-danger shadow-sm" data-bs-toggle="modal" data-bs-target="#campusModal">
									<span>
										<i class="bi bi-trash text-white"></i>
									</span>
									Delete
								</button>
							</div>
						}

						<div class="ms-auto">
							<a asp-area="Administrator" asp-page="/Campuses/Index" class="btn btn-secondary shadow-sm">Cancel</a>
							@if (Model.Campus.Id != 0)
							{
								<input asp-page-handler="EditCampus" type="submit" class="btn btn-primary shadow-sm" value="Save" />
							}
							else
							{
								<input asp-page-handler="CreateCampus" type="submit" class="btn btn-primary shadow-sm" value="Save" />
							}
						</div>
					</div>
					<!-- End of Submit buttons -->
				</form>
			</div>
		</div>
	</div>
</div>
<!-- Start of modal-->
<div class="modal" id="campusModal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete Campus</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to <b class="text-danger">delete</b> this campus?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				<input asp-page-handler="DeleteCampus" type="submit" form="campusForm" class="btn btn-danger" value="Delete" />
			</div>
		</div>
	</div>
</div>
<!-- End of modal-->
@section Scripts {
	<script>
		class CampusController {
			/**
			* See if requried. True = required
			* @@type {boolean}
			*/
			#Campus = true;
			#CampusID = 'Campus_CampusName';
			#CampusSelector = '[data-valmsg-for="Campus.CampusName"]';

			#Address1 = true;
			#Address1ID = 'Campus_Address1';
			#Address1Selector = '[data-valmsg-for="Campus.Address1"]';

			#City = true;
			#CityID = 'Campus_City';
			#CitySelector = '[data-valmsg-for="Campus.City"]';

			#State = true;
			#StateID = 'Campus_State';
			#StateSelector = '[data-valmsg-for="Campus.State"]';

			#Country = true;
			#CountryID = 'Campus_Country';
			#CountrySelector = '[data-valmsg-for="Campus.Country"]';

			#Zip = true;
			#ZipID = 'Campus_Zip';
			#ZipSelector = '[data-valmsg-for="Campus.Zip"]';

			/**
			 * If the select field is requireds make it editable.
			 * If not disable the input and set it to empty
			 * @@param {string} Id The Id for the Input
			 * @@param {string} ErrorQuery The Query for the Error DOM element\
			 * @@param {boolean} toggle If we are making the param required
			*/
			#requirefield(Id, ErrorQuery, toggle) {
				let object = document.getElementById(Id);
				let NoneOption = object.options[object.options.length - 1];
				if (toggle) {
					if (object.value == '') {
						object.options.selectedIndex = 0;
					}
					object.disabled = false;
					NoneOption.style.display = 'none';
				}
				else {
					object.options.selectedIndex = object.options.length - 1;
					object.disabled = true;
					NoneOption.style.display = 'initial';
				}
				let span = $(ErrorQuery)[0];
				span.innerText = "";
			}

			/**
			 * @@param {string} Id The Id for the Input
			 * @@param {string} ErrorQuery The Query for the Error DOM element
			 * @@returns {boolean} Returns true if there is an error
			*/
			#validateRequirement(Id, ErrorQuery) {
				let object = document.getElementById(Id);
				let span = $(ErrorQuery)[0];

				if (object.value == "") {
					span.innerText = "Please enter a value.";
					return true;
				}
				else {
					span.innerText = "";
				}
				return false;
			}

			/**
			 * Validate all the fields. If they are return true, and if not display error messages
			 * @@returns {boolean} returns true if valid
			 */
			validateFields() {
				let isValid = true;

				if (this.#validateRequirement(this.#CampusID, this.#CampusSelector)) {
					isValid = false;
				}

				if (this.#validateRequirement(this.#Address1ID, this.#Address1Selector)) {
					isValid = false;
				}

				if (this.#validateRequirement(this.#CityID, this.#CitySelector)) {
					isValid = false;
				}

				if (this.#validateRequirement(this.#StateID, this.#StateSelector)) {
					isValid = false;
				}

				if (this.#validateRequirement(this.#CountryID, this.#CountrySelector)) {
					isValid = false;
				}

				if (this.#validateRequirement(this.#ZipID, this.#ZipSelector)) {
					isValid = false;
				}

				return isValid;
			}
		};
		// initulize the preferences right away
		let campusController = new CampusController();

		function validateForm() {
			let isValid = true;

			if (!campusController.validateFields()) {
				isValid = false;
			}

			return isValid;
		}
	</script>

}