CASPAR/Areas/ProgramCoordinator/Controllers/CourseSectionController.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.ApplicationCore.ViewModels;
using CASPAR.ApplicationCore.ViewModels.Input;
using CASPAR.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Omu.Awem.Utils;
using Omu.AwesomeMvc;
using System.Linq;
using System.Reflection;

namespace CASPAR.Areas.ProgramCoordinator.Controllers
{
    public class CourseSectionController : Controller
    {
        private UnitOfWork _unitOfWork;
        private string Includes = "SemesterSchedule,SemesterSchedule.Semester,Course,Instructor,Modality,Status,Classroom,Classroom.Building,Classroom.Building.Campus,TimeSlot,DayOfTheWeek,PayModel,WhoPays";
        public CourseSectionController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        private object GetMappingFromCourseSection(CourseSection o)
        {
            return new
            {
                Id = o.CourseSectionID,
                o.PartOfTerm,
                CName = NullableFieldsHelper(o.Course, () => o.Course.CourseName),
                Mode = NullableFieldsHelper(o.Modality, () => o.Modality.ModalityType),
                InstructorName = NullableFieldsHelper(o.Instructor, () => o.Instructor.LastName + " " + o.Instructor.FirstName),
                Loc = NullableFieldsHelper(o.Classroom, () => o.Classroom.Building.Campus.CampusName),
                Days = NullableFieldsHelper(o.DayOfTheWeek, () => o.DayOfTheWeek.DayOfWeek),
                Time = NullableFieldsHelper(o.TimeSlot, () => o.TimeSlot.TimeSlotType),
                Stat = NullableFieldsHelper(o.Status, () => o.Status.StatusType),
                ClassroomNum = NullableFieldsHelper(o.Classroom, () => GetClassroomName(o.Classroom)),
                o.MaxEnrollment,
                o.FirstDayEnrollment,
                o.ThirdWeekEnrollment,
                o.CRN,
                o.CourseID,
                WhoPays = o.WhoPays.WhoPaysType,
                o.SectionNotes,
                PayMod = o.PayModel.PayModelType,
                o.SemesterScheduleID,
                o.ClassRoomID,
                SemesterId = o.SemesterSchedule.SemesterID
            };
        }

        private string GetClassroomName(Classroom c)
        {
            return c.Building.BuildingName + " " + c.RoomNum.ToString();
        }

        public IActionResult GetCourseSections(GridParams g, int? semesterId)
        {
            // this just tests to see if semester id is null and if it is, then it sets it to 1
            semesterId = semesterId ?? 1;

            var courseSection = _unitOfWork.SECTION.GetAll(includes: Includes);


            var gridModel = new GridModelBuilder<CourseSection>(courseSection.AsQueryable(), g);

            gridModel.KeyProp = o => o.CourseSectionID;
            gridModel.Map = GetMappingFromCourseSection;

            var jsonOut = Json(gridModel.Build());
            return jsonOut;
        }

        public IActionResult GetModality()
        {
            var modality = _unitOfWork.Modality.GetAll();

            return Json(modality.Select(o => new KeyContent(o.Id, o.ModalityType)));
        }

        public IActionResult GetDaysOfTheWeek()
        {
            var daysOfTheWeek = _unitOfWork.DAY_OF_WEEK.GetAll();

            return Json(daysOfTheWeek.Select(o => new KeyContent(o.DayOfTheWeekID, o.DayOfWeek)));
        }

        public IActionResult GetInstructors()
        {
            var instructor = _unitOfWork.Instructor.GetAll();

            return Json(instructor.Select(o => new KeyContent(o.Id, o.FirstName + " " + o.LastName)));
        }

        public IActionResult GetTimeSlot()
        {
            var timeSlot = _unitOfWork.TimeSlot.GetAll();

            return Json(timeSlot.Select(o => new KeyContent(o.TimeSlotID, o.TimeSlotType)));
        }

        public IActionResult GetStatus()
        {
            var status = _unitOfWork.Status.GetAll();

            return Json(status.Select(o => new KeyContent(o.StatusID, o.StatusType)));
        }

        public IActionResult GetClassroom()
        {
            var classroom = _unitOfWork.Classroom.GetAll(includes: "Building,Building.Campus");

            return Json(classroom.Select(o => new KeyContent(o.ClassRoomID, ClassroomName(o))));
        }

        public IActionResult GetCourses()
        {
            var course = _unitOfWork.Course.GetAll();

            return Json(course.Select(o => new KeyContent(o.CourseID, o.CourseNumber + " " + o.CourseName)));
        }

        public IActionResult GetPayModel()
        {
            var payModel = _unitOfWork.PayModel.GetAll();

            return Json(payModel.Select(o => new KeyContent(o.PayModelID, o.PayModelType)));
        }

        public IActionResult GetWhoPays()
        {
            var whoPays = _unitOfWork.WhoPays.GetAll();

            return Json(whoPays.Select(o => new KeyContent(o.WhoPaysID, o.WhoPaysType)));
        }

        private string ClassroomName(Classroom c)
        {
            return c.Building.Campus.CampusName + " " + c.Building.BuildingName + " " + c.RoomNum;
        }

        public IActionResult Delete(int id)
        {
            var course = _unitOfWork.SECTION.GetById(id);

            return PartialView(new DeleteConfirmInput
            {
                Id = id,
                Message = "Are you sure you want to nuke the ever living fuck out of the small boi?",
                GridId = "Sections"
            }) ;
        }

        [HttpPost]
        public IActionResult Delete(DeleteConfirmInput input)
        {
            _unitOfWork.SECTION.Delete(_unitOfWork.SECTION.GetById(input.Id));

            // the PopupForm's success function utils.itemDeleted expects an obj with "Id" property
            return Json(new { input.Id });
        }

        [HttpPost]
        public IActionResult Save(CourseSectionInput input)
        {

            //if (ModelState.IsValid) this isn't working.  The Id from the input can be zero and it is set to validate never, but the model keeps saying that the id is the problem
            if (true)
                {
                var isCreate = input.Id == 0;

                var course = isCreate ? new CourseSection() :
                    _unitOfWork.SECTION.GetById(input.Id);

                if (course == null)
                {
                    throw new Exception("Item doesn't exist anymore, id:" + input.Id);
                }

                course.MaxEnrollment = input.MaxEnrollment ?? course.MaxEnrollment;
                course.PartOfTerm = input.PartOfTerm ?? course.PartOfTerm;
                course.ThirdWeekEnrollment = input.ThirdWeekEnrollment ?? course.ThirdWeekEnrollment;
                course.FirstDayEnrollment = input.FirstDayEnrollment ?? course.FirstDayEnrollment;
                course.CRN = input.CRN ?? course.CRN;
                course.ClassRoomID = input.ClassroomId ?? course.ClassRoomID;
                course.StatusID = input.StatusId ?? course.StatusID;
                course.TimeSlotID = input.TimeSlotId ?? course.TimeSlotID;
                course.DayOfWeekID = input.DaysOfTheWeekId ?? course.DayOfWeekID;
                course.ModalityID = input.ModalityId ?? course.ModalityID;
                course.StatusID = input.StatusId ?? course.StatusID;
                course.WNumber = input.InstructorId ?? course.WNumber;
                course.CourseID = input.CourseId ?? course.CourseID;
                course.WhoPaysID = input.WhoPaysID ?? course.WhoPaysID;
                course.PayModelID = input.PayModelID ?? course.PayModelID;
                course.SectionNotes = input.SectionNotes ?? course.SectionNotes;

                //Semester schedule needs to be removed from the course section.  Or I have no idea what it is linked to
                course.SemesterScheduleID = _unitOfWork.SemesterSchedule.Get(o => o.SemesterScheduleID != 0).SemesterScheduleID;

                if (isCreate)
                {
                    _unitOfWork.SECTION.Add(course);
                }
                else
                {
                    _unitOfWork.SECTION.Update(course);
                }

                course = _unitOfWork.SECTION.Get(o => o.CourseSectionID == course.CourseSectionID, includes: Includes);

                return Json(new { Item = GetMappingFromCourseSection(course) });
            }

            return Json(ModelState.GetErrorsInline());
        }

        public IActionResult PopupInterests(int id)
        {
            return PartialView("StudentPreferences", id);
        }

        // The classrooms currently don't sort based on the semester.  I'm not sure why I had the classroom id though
        public IActionResult ClassroomUsedIn(int classRoomID, int semesterScheduleID)
        {
            return PartialView("ClassroomUsedIn");
        }

        public IActionResult GetItem(int? v)
        {
            var o =  _unitOfWork.Classroom.Get(o => o.ClassRoomID == v, includes: "Building") ?? new Classroom();

            return Json(new KeyContent(o.ClassRoomID, GetClassroomName(o)));
        }

        public IActionResult GetInterest(GridParams g)
        {
            var semesterIdTemp = 1;
            var preferences = _unitOfWork.StudentPreferences.GetAll(o => o.SemesterID == semesterIdTemp);
            var grouped = preferences.GroupBy(o => new { o.ModalityID, o.CampusID, o.TimeOfDayID, o.CourseID })
                .Select(group => 
                new StudentInterestDisplay
                { 
                    ModalityId = _unitOfWork.Modality.GetById(group.Key.ModalityID).ModalityType,
                    CampusId = _unitOfWork.Campus.GetById(group.Key.CampusID)?.CampusName ?? "",
                    TimeOfDayID = _unitOfWork.TimeOfDay.GetById(group.Key.TimeOfDayID)?.Time ?? "",
                    Count = group.Count(),
                    CourseName = _unitOfWork.Course.GetById(group.Key.CourseID)?.CourseName ?? ""
                });

            int i = 1;

CASPAR/Areas/ProgramCoordinator/Controllers/TeacherPreferencesController.cs
using CASPAR.ApplicationCore.Models;
using CASPAR.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Omu.AwesomeMvc;
using CASPAR.ApplicationCore.ViewModels;

namespace CASPAR.Areas.ProgramCoordinator.Controllers
{
    public class TeacherPreferencesController : Controller
    {

        private UnitOfWork _unitOfWork;
        public TeacherPreferencesController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult TeacherPref()
        {
            //return PartialView("TeacherPreferences", SemesterId + "," + CourseId) ;
            return PartialView();
            //return PartialView(new CASPAR.Pages.Shared.TeacherPreferencesModel { _SemesterId = SemesterId ?? 0, _CourseId = CourseId ?? 0 });
        }

        public IActionResult GetTeacherPrefs(GridParams g, string? SemesterAndCourseId)
        {
            var split = SemesterAndCourseId.Split(',');
            int semesterId = int.Parse(split[0]);
            int courseId = int.Parse(split[1]);


            var teacherPrefs = _unitOfWork.InstructorPreferences.GetAll(o => o.SemesterID == semesterId && o.CourseID == courseId, includes: "Modality,Campus,ApplicationUser");

            var gridModel = new GridModelBuilder<InstructorPreferences>(teacherPrefs.AsQueryable(), g);

            gridModel.KeyProp = o => o.PreferenceDetailsID;
            gridModel.Map = o => new 
            {
                o.PreferencesRank,
                Mod = o.Modality.ModalityType,
                Loc = o.Campus?.CampusName ?? "",
                Name = o.ApplicationUser.FirstName + " " + o.ApplicationUser.LastName
            };

            var jsonOut = Json(gridModel.Build());
            return jsonOut;
        }

        public IActionResult GetItem(int? v)
        {
            var o = _unitOfWork.InstructorPreferences.GetById(v);

            return Json(new KeyContent(o.WNumber, o.ApplicationUser.FirstName + " " + o.ApplicationUser.LastName));
        }
    }
}

CASPAR/Areas/ProgramCoordinator/Pages/CourseSection/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CASPAR.Areas.ProgramCoordinator.Pages.CourseSection
{
    public class IndexModel : PageModel
    {
        public int? ClassroomID { get; set; }
        public int? InstructorID { get; set; }
        public void OnGet()
        {
        }
    }
}

CASPAR/Areas/ProgramCoordinator/Pages/CourseSection/Index.cshtml
@page
@model CASPAR.Areas.ProgramCoordinator.Pages.CourseSection.IndexModel
@{
    var gridName = "Sections";
    var controllerName = "CourseSection";
    ViewData["Title"] = "Sections";
}




@(
Html.Awe().Grid(gridName)
.Mod(o => o.Main()
.InlineEdit(Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.Save), controllerName)))
.Columns(
    new Column { Bind = "Course.CourseName", ClientFormat = ".(CName)", PercentWidth = 10 },
    Html.InlEditColumn(),
    new Column { Bind = "PartOfTerm", Header = "Part of Term", PercentWidth = 3 }.InlString(),
    new Column { Bind = "Modality.ModalityType", ClientFormat = ".(Mode)", Prop = "Mode", PercentWidth = 3 }
    .InlDropdownList(new DropdownListOpt
    {
        Name = "ModalityId",
        Url = Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetModality), controllerName)
    }),
    new Column { Bind = "Instructor.LastName,Instructor.FirstName", ClientFormat = ".(InstructorName)", PercentWidth = 5 }
    @*.Inl(Html.Awe().LookupFor(o => o.InstructorID)
            .LookupGrid(Url.Action("TeacherPref", "TeacherPreferences", new { SemesterId = ".(SemesterId)", CourseId = ".(CourseID)" }))
            .Controller("TeacherPreferences")),*@
    .InlDropdownList(new DropdownListOpt
    {
        Name = "InstructorId",
        Url = Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetInstructors), controllerName)
    }),
    new Column { Bind = "Classroom.Building.Campus.CampusName", ClientFormat = ".(Loc)", Header = "Location", PercentWidth = 10 },
    new Column { Bind = "DayOfTheWeek.DayOfWeek", ClientFormat = ".(Days)", Header = "Day of week", PercentWidth = 3 }
    .InlDropdownList(new DropdownListOpt
    {
        Name = "DaysOfTheWeekId",
        Url = Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetDaysOfTheWeek), controllerName)
    }),
    new Column { Bind = "TimeSlot.TimeSlotType", ClientFormat = ".(Time)", Header = "Time Slot", PercentWidth = 3 }
    .InlDropdownList(new DropdownListOpt
    {
        Name = "TimeSlotId",
        Url = Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetTimeSlot), controllerName)
    }),
    new Column { Bind = "Status.StatusType", ClientFormat = ".(Stat)", PercentWidth = 5 }
    .InlDropdownList(new DropdownListOpt
    {
        Name = "StatusId",
        Url = Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetStatus), controllerName)
    }),
    new Column { Bind = "Classroom.Building.BuildingName,Classroom.RoomNum", ClientFormat = ".(ClassroomNum)", Header = "Classroom", PercentWidth = 10 }
    .Inl(Html.Awe().LookupFor(o => o.ClassroomID)
            .LookupGrid(Url.Action("ClassroomUsedIn", "CourseSection", new { classRoomID = ".(classRoomID)", semesterScheduleID = ".(semesterScheduleID)" }))
            .Controller("CourseSection")),
    new Column { Bind = "WhoPays.WhoPaysType", ClientFormat = ".(WhoPays)", Header = "Who Pays", PercentWidth = 5 },
    new Column { Bind = "PayModel.PayModelType", ClientFormat = ".(PayMod)", Header = "Pay Model", PercentWidth = 5 },
    new Column { Bind = "MaxEnrollment", Header = "Max Enrollment", PercentWidth = 2 }
    .InlString(),
    new Column { Bind = "FirstDayEnrollment", Header = "First Day Enrollment", PercentWidth = 2 },
    new Column { Bind = "ThirdWeekEnrollment", Header = "Third Week Enrollment", PercentWidth = 2 },
    new Column { Bind = "Crn", PercentWidth = 5 },
    new Column { Bind = "SectionNotes", Header = "Section Notes", PercentWidth = 10 }
    .InlString(),
    new Column { Bind = "Id" }.InlId(),
    Html.InlDeleteColumn(gridName)
)
.Url(Url.Action(nameof(CASPAR.Areas.ProgramCoordinator.Controllers.CourseSectionController.GetCourseSections), controllerName))
.Height(1000)
.PercentWidth(100)
)

@(Html.Awe().Grid("Preferences").Columns(
    new Column { Bind = "ModalityId" },
    new Column { Bind = "CampusId" },
    new Column { Bind = "TimeOfDayID" },
    new Column { Bind = "Count" },
    new Column { Bind = "CourseName" }
).Url(Url.Action("GetInterest", "CourseSection"))
.Width(700)
.Height(500)

)

//@(Html.BindOVldForId<CourseSectionInput>(gridName))